export = {
  overrides: [
    {
      files: ['*.ts'],
      plugins: ['@typescript-eslint', '@angular-eslint', 'editorconfig', 'prettier'],
      extends: [
        'plugin:@typescript-eslint/all',
        'plugin:@angular-eslint/all',
        'plugin:editorconfig/all',
        'plugin:prettier/recommended',
      ],
      rules: {
        '@angular-eslint/component-class-suffix': 'warn',
        '@angular-eslint/component-max-inline-declarations': ['warn', { template: 10, styles: 10 }],
        '@angular-eslint/component-selector': 'warn',
        '@angular-eslint/contextual-decorator': 'warn',
        '@angular-eslint/contextual-lifecycle': 'warn',
        '@angular-eslint/directive-class-suffix': 'warn',
        '@angular-eslint/directive-selector': 'warn',
        '@angular-eslint/no-attribute-decorator': 'warn',
        '@angular-eslint/no-conflicting-lifecycle': 'warn',
        '@angular-eslint/no-empty-lifecycle-method': 'warn',
        '@angular-eslint/no-forward-ref': 'warn',
        '@angular-eslint/no-host-metadata-property': 'warn',
        '@angular-eslint/no-input-prefix': 'warn',
        '@angular-eslint/no-input-rename': 'warn',
        '@angular-eslint/no-inputs-metadata-property': 'warn',
        '@angular-eslint/no-lifecycle-call': 'warn',
        '@angular-eslint/no-output-native': 'warn',
        '@angular-eslint/no-output-on-prefix': 'warn',
        '@angular-eslint/no-output-rename': 'warn',
        '@angular-eslint/no-outputs-metadata-property': 'warn',
        '@angular-eslint/no-pipe-impure': 'warn',
        '@angular-eslint/no-queries-metadata-property': 'warn',
        '@angular-eslint/pipe-prefix': 'warn',
        '@angular-eslint/prefer-on-push-component-change-detection': 'warn',
        '@angular-eslint/prefer-output-readonly': 'warn',
        '@angular-eslint/relative-url-prefix': 'warn',
        '@angular-eslint/sort-ngmodule-metadata-arrays': 'warn',
        '@angular-eslint/use-component-selector': 'warn',
        '@angular-eslint/use-component-view-encapsulation': 'warn',
        '@angular-eslint/use-injectable-provided-in': 'off',
        '@angular-eslint/use-lifecycle-interface': 'warn',
        '@angular-eslint/use-pipe-transform-interface': 'warn',

        '@typescript-eslint/adjacent-overload-signatures': 'warn',
        '@typescript-eslint/array-type': 'warn',
        '@typescript-eslint/await-thenable': 'warn',
        '@typescript-eslint/ban-ts-comment': 'warn',
        '@typescript-eslint/ban-tslint-comment': 'warn',
        '@typescript-eslint/ban-types': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/brace-style': 'warn',
        '@typescript-eslint/class-literal-property-style': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/comma-dangle': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/comma-spacing': 'warn',
        '@typescript-eslint/consistent-indexed-object-style': 'warn',
        '@typescript-eslint/consistent-type-assertions': 'warn',
        '@typescript-eslint/consistent-type-definitions': 'warn',
        '@typescript-eslint/consistent-type-imports': ['warn', { prefer: 'no-type-imports' }],
        '@typescript-eslint/consistent-type-exports': 'warn',
        '@typescript-eslint/default-param-last': 'warn',
        '@typescript-eslint/dot-notation': 'warn',
        '@typescript-eslint/explicit-function-return-type': 'warn',
        '@typescript-eslint/explicit-member-accessibility': 'warn',
        '@typescript-eslint/explicit-module-boundary-types': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/func-call-spacing': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/indent': 'off',
        '@typescript-eslint/init-declarations': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/keyword-spacing': 'warn',
        '@typescript-eslint/lines-between-class-members': ['warn', { exceptAfterSingleLine: true }],
        // disabled by prettier, don't override '@typescript-eslint/member-delimiter-style': 'warn',
        '@typescript-eslint/member-ordering': 'warn',
        '@typescript-eslint/method-signature-style': 'warn',
        '@typescript-eslint/naming-convention': 'warn',
        '@typescript-eslint/no-array-constructor': 'warn',
        '@typescript-eslint/no-base-to-string': 'warn',
        '@typescript-eslint/no-confusing-non-null-assertion': 'warn',
        '@typescript-eslint/no-confusing-void-expression': 'warn',
        '@typescript-eslint/no-dupe-class-members': 'warn',
        '@typescript-eslint/no-duplicate-imports': 'warn',
        '@typescript-eslint/no-dynamic-delete': 'warn',
        '@typescript-eslint/no-empty-function': 'warn',
        '@typescript-eslint/no-empty-interface': 'warn',
        '@typescript-eslint/no-explicit-any': 'warn',
        '@typescript-eslint/no-extra-non-null-assertion': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/no-extra-parens': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/no-extra-semi': 'warn',
        '@typescript-eslint/no-extraneous-class': ['warn', { allowStaticOnly: true, allowWithDecorator: true }],
        '@typescript-eslint/no-floating-promises': 'warn',
        '@typescript-eslint/no-for-in-array': 'warn',
        '@typescript-eslint/no-implied-eval': 'warn',
        '@typescript-eslint/no-inferrable-types': 'off',
        '@typescript-eslint/no-invalid-this': 'warn',
        '@typescript-eslint/no-invalid-void-type': 'warn',
        '@typescript-eslint/no-loop-func': 'warn',
        '@typescript-eslint/no-loss-of-precision': 'warn',
        '@typescript-eslint/no-magic-numbers': 'off',
        '@typescript-eslint/no-meaningless-void-operator': 'warn',
        '@typescript-eslint/no-misused-new': 'warn',
        '@typescript-eslint/no-misused-promises': 'warn',
        '@typescript-eslint/no-namespace': 'warn',
        '@typescript-eslint/no-non-null-asserted-nullish-coalescing': 'warn',
        '@typescript-eslint/no-non-null-asserted-optional-chain': 'warn',
        '@typescript-eslint/no-non-null-assertion': 'warn',
        '@typescript-eslint/no-parameter-properties': 'off',
        '@typescript-eslint/no-redeclare': 'warn',
        '@typescript-eslint/no-require-imports': 'warn',
        '@typescript-eslint/no-restricted-imports': 'warn',
        '@typescript-eslint/no-shadow': 'warn',
        '@typescript-eslint/no-this-alias': 'warn',
        '@typescript-eslint/no-throw-literal': 'warn',
        '@typescript-eslint/no-type-alias': 'off',
        '@typescript-eslint/no-unnecessary-boolean-literal-compare': 'warn',
        '@typescript-eslint/no-unnecessary-condition': 'off',
        '@typescript-eslint/no-unnecessary-qualifier': 'warn',
        '@typescript-eslint/no-unnecessary-type-arguments': 'warn',
        '@typescript-eslint/no-unnecessary-type-assertion': 'warn',
        '@typescript-eslint/no-unnecessary-type-constraint': 'warn',
        '@typescript-eslint/no-unsafe-argument': 'warn',
        '@typescript-eslint/no-unsafe-assignment': 'warn',
        '@typescript-eslint/no-unsafe-call': 'warn',
        '@typescript-eslint/no-unsafe-member-access': 'warn',
        '@typescript-eslint/no-unsafe-return': 'warn',
        '@typescript-eslint/no-unused-expressions': 'warn',
        '@typescript-eslint/no-unused-vars': 'warn',
        '@typescript-eslint/no-use-before-define': 'warn',
        '@typescript-eslint/no-useless-constructor': 'warn',
        '@typescript-eslint/no-var-requires': 'warn',
        '@typescript-eslint/non-nullable-type-assertion-style': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/object-curly-spacing': ['warn', 'always'],
        '@typescript-eslint/padding-line-between-statements': 'warn',
        '@typescript-eslint/parameter-properties': 'off',
        '@typescript-eslint/prefer-as-const': 'warn',
        '@typescript-eslint/prefer-enum-initializers': 'warn',
        '@typescript-eslint/prefer-for-of': 'warn',
        '@typescript-eslint/prefer-function-type': 'warn',
        '@typescript-eslint/prefer-includes': 'warn',
        '@typescript-eslint/prefer-literal-enum-member': 'warn',
        '@typescript-eslint/prefer-namespace-keyword': 'warn',
        '@typescript-eslint/prefer-nullish-coalescing': 'warn',
        '@typescript-eslint/prefer-optional-chain': 'warn',
        '@typescript-eslint/prefer-readonly': 'off',
        '@typescript-eslint/prefer-readonly-parameter-types': 'off',
        '@typescript-eslint/prefer-reduce-type-parameter': 'warn',
        '@typescript-eslint/prefer-regexp-exec': 'warn',
        '@typescript-eslint/prefer-return-this-type': 'warn',
        '@typescript-eslint/prefer-string-starts-ends-with': 'warn',
        '@typescript-eslint/promise-function-async': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/quotes': 'warn',
        '@typescript-eslint/require-array-sort-compare': 'warn',
        '@typescript-eslint/require-await': 'warn',
        '@typescript-eslint/restrict-plus-operands': 'warn',
        '@typescript-eslint/restrict-template-expressions': 'warn',
        '@typescript-eslint/return-await': ['warn', 'in-try-catch'],
        // disabled by prettier, don't override '@typescript-eslint/semi': 'warn',
        '@typescript-eslint/sort-type-union-intersection-members': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/space-before-function-paren': ['warn', { anonymous: 'always', asyncArrow: 'always', named: 'never' }],
        // disabled by prettier, don't override '@typescript-eslint/space-infix-ops': 'warn',
        '@typescript-eslint/strict-boolean-expressions': ['warn', { allowNullableString: true }],
        '@typescript-eslint/switch-exhaustiveness-check': 'off',
        '@typescript-eslint/triple-slash-reference': 'warn',
        // disabled by prettier, don't override '@typescript-eslint/type-annotation-spacing': 'warn',
        '@typescript-eslint/typedef': 'warn',
        '@typescript-eslint/unbound-method': ['warn', { ignoreStatic: true }],
        '@typescript-eslint/unified-signatures': 'warn',

        'editorconfig/indent': 'off',
      },
    },
  ],
};
